from django.urls import path, include
from .views import *

app_name = 'Shopping'

urlpatterns = [
    path("", index, name="Shopping"),
    path("ContactUs", ContactUs, name='ContactUs'),
    path('login', loginUser, name='login'),
    path('logout', UserLogout, name='logout'),
    path('signupform', signupform, name='signupform'),
    path('search', product_search.as_view(), name='search'),
    path('Detail/<pk>/', Detail, name='Detail'),
    # path('AllProduct/<item>/',AllProduct.as_view(),name='AllProduct'),
    path('AllProduct', AllProduct, name='AllProduct'),
    path('categorydata', categorydata, name='categorydata'),
    path('cart/add/<int:id>/', cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         item_increment, name='item_increment'),
    path('cart/item_increment_qty/<int:id>/<int:qty>/',
         item_increment_qty, name='item_increment_qty'),
    path('cart/item_decrement/<int:id>/', item_decrement, name='item_decrement'),
    path('cart/cart_clear/', cart_clear, name='cart_clear'),
    path('cart/cart-detail/', cart_detail, name='cart_detail'),
    path('checkout', checkout_form, name='checkout'),
    path('thanks', thanksyou, name='thanks'),
    path('myaccount', MyAccount.as_view(), name='myaccount'),
    path('bill/billdetail/<int:id>', billdetailspage, name="billdetail"),
    path('TrackingModel', TrackingView.as_view(), name="TrackingModel"),
    path('News', newsupdate, name="News"),
    path('unsubscribe', unsubscribe, name="unsubscribe"),
    path('APIview', APIview.as_view(), name="APIview"),
    path('APIviewSignUp', APIviewSignUp.as_view(), name="APIviewSignUp"),
    path('accDetail', accDetail, name='accDetail'),
    path('wishlist/add/<int:id>/', wistlist_add, name='wishlist'),
    path('wishlist/delete/<int:id>/', remove_wishlist_item, name='wishlistdelete'),
    path('wishlist_detail', wistlist_detail, name='wishlist_detail'),
    path('wishlistdeleteall', wishlistdeleteall, name='wishlistdeleteall'),
    path('compareList/add/<int:id>/', compareList_add, name='compareList'),
    path('compareList_detail', compareList_detail, name='compareList_detail'),
    path('compareListdeleteall', compareListdeleteall, name='compareListdeleteall'),
    path('ForgetEmail', ForgetEmail, name='change_password'),
    path('forgetPasswordPage', forgetPasswordPage, name='forgetPasswordPage'),
    path('change_password', change_password, name='change_password'),
    path('applyCouponCode', applyCouponCode, name='applyCouponCode'),
    path('cancelorder', cancelorder, name='cancelorder'),
    path('myprofile', myprofile, name='myprofile'),
    path('staff_profile', staff_profile.as_view(), name='staff_profile'),
    path('staff_profile_update/<int:id>/', staff_profile_update, name='staff_profile_update'),
    path('review', review, name='review'),
    path('comment', comment, name='comment'),
    path('loadcomment', loadcomment, name='loadcomment'),

    path('commentpage', commentpage, name='commentpage'),
]
