# Generated by Django 3.1 on 2020-08-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dod',
            field=models.BooleanField(default=False, verbose_name='Deal of Day'),
        ),
    ]
