# Generated by Django 3.1 on 2020-08-16 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0005_auto_20200815_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shopping.coupon', verbose_name='Apply Coupon'),
        ),
    ]
