# Generated by Django 3.1 on 2020-08-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0006_bill_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.PositiveIntegerField(verbose_name='Ratings'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=255, verbose_name='user'),
        ),
    ]
