# Generated by Django 3.1 on 2020-08-21 08:09

import Shopping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0007_auto_20200821_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='review',
            name='phn',
            field=models.IntegerField(blank=True, null=True, validators=[Shopping.models.phn_no_validation], verbose_name='Phone number'),
        ),
    ]
